### ISSUE TITLE
How to combine this and WordPress

### ISSUE THREAD

**Issue by davidrhoderick** [hyyan/brunch-with-hyyan#1]
I'm really glad that there is a Brunch skeleton that can work with WordPress, but you aren't very explicit on how to integrate the two.  How does it work for you?  Where do I build my Brunch project or where to I install WordPress?  Do I still use MAMP or another PHP/MySQL local server to view the site or do I use the Brunch server?

**Comment by hyyan** [comment]
@davidrhoderick the skeleton is used in this start theme https://github.com/hyyan/brunch-wordpress-theme as example , it is very simple theme that can be used in production safely. which integrates brunch workflow with wordpress. 

To view the site you will need a sever , like MAMP or WAMP , brunch server won't server PHP Files

**Comment by davidrhoderick** [comment]
Thanks it is working great !

**Comment by hyyan** [comment]
@davidrhoderick glade to hear
