### ISSUE TITLE
Additional js libriarias

### ISSUE THREAD

**Issue by sera2007** [hyyan/brunch-with-hyyan#3]
First full great thanks for your work!
I have a problem with additional js libraries. I will try to store them in app/assets/scripts folder , but the compiling process compile index.js file first and after other files. As result - all functions from additional files don't work, because of lately including.

http://take.ms/QrE4p - file structure and additional js library (jquery plugin)
http://take.ms/loWqY - index.js
and compiled app.js http://take.ms/Kq3sB - you can see that the initialization of slick is before the slick library code includes(

Do you have any ideas how to fix it ?

**Comment by hyyan** [comment]
What about https://api.jquery.com/ready/

**Comment by sera2007** [comment]
Ohh, such a simple error(( thanks for fast answer!
